import { 
  AreaChart, 
  Area, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip as RechartsTooltip, 
  ResponsiveContainer,
  BarChart,
  Bar
} from 'recharts';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { UsageComingSoon } from './UsageComingSoon';

interface UsageChartsProps {
  metrics: any;
  hasLiveMetrics: boolean;
}

export function UsageCharts({ metrics, hasLiveMetrics }: UsageChartsProps) {
  const chartData = hasLiveMetrics ? metrics.bookings.map((val: number, i: number) => ({
    name: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'][i] || `M${i + 1}`,
    bookings: val,
    revenue: metrics.revenue?.[i] ?? 0
  })) : [];

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
      <Card className="shadow-sm border-none bg-white">
        <CardHeader>
          <CardTitle className="font-serif text-lg">Booking Volume</CardTitle>
          <CardDescription>Historical booking activity for the last 6 months.</CardDescription>
        </CardHeader>
        <CardContent className="h-[300px]">
          {hasLiveMetrics ? (
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={chartData}>
                <defs>
                  <linearGradient id="colorBook" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#C9973A" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#C9973A" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f0f0f0" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize: 10}} />
                <YAxis axisLine={false} tickLine={false} tick={{fontSize: 10}} />
                <RechartsTooltip />
                <Area type="monotone" dataKey="bookings" stroke="#C9973A" fillOpacity={1} fill="url(#colorBook)" />
              </AreaChart>
            </ResponsiveContainer>
          ) : (
            <UsageComingSoon 
              title="Historical Analytics" 
              description="Aggregated booking patterns and historical performance metrics will be implemented soon." 
            />
          )}
        </CardContent>
      </Card>

      <Card className="shadow-sm border-none bg-white">
        <CardHeader>
          <CardTitle className="font-serif text-lg">Revenue Contribution</CardTitle>
          <CardDescription>Monthly revenue generated by this property.</CardDescription>
        </CardHeader>
        <CardContent className="h-[300px]">
          {hasLiveMetrics ? (
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f0f0f0" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize: 10}} />
                <YAxis axisLine={false} tickLine={false} tick={{fontSize: 10}} />
                <RechartsTooltip />
                <Bar dataKey="revenue" fill="#0F1B2D" radius={[4, 4, 0, 0]} barSize={20} />
              </BarChart>
            </ResponsiveContainer>
          ) : (
            <UsageComingSoon 
              title="Revenue Tracking" 
              description="Live revenue stream monitoring and financial forecasting will be implemented soon." 
            />
          )}
        </CardContent>
      </Card>
    </div>
  );
}
